### ISSUE TITLE
Graphische Optionen

### ISSUE THREAD

**Issue by Michail-Okunew** [ThoJor/Inf-Q2b-Interferenz#21]
Das Programm lässt sich nicht ausführen, in den graphischen Optionen wird mehr Arbeitsspeicher benötigt, als zur Verfügung steht (>8GB) - ohne den Rest des Programms (also in einer Testumgebung) funktioniert es allerdings.

**Comment by ThoJor** [comment]
Kannst du herausfinden, wo genau er die 8GB (bzw. mehr) fordert?

Denn: woher weißt du, dass das Problem bei den graphischen Optionen liegt, welche eigentlich kaum RAM benötigen. Aus dem Quellcode ist das nämlich nicht ersichtlich (für mich).
Außerdem liegt das Problem nicht bei den graphischen Optionen, wenn diese in einer (geeigneten) Testumgebung einwandfrei funktionieren.

Funktioniert das Programm ohne die graphischen Optionen?

**Comment by Michail-Okunew** [comment]
Ohne die graphischen Optionen funktioniert das Programm soweit einwandfrei. Der Fehler tritt nur auf, wenn ich versuche, das Programm inklusive der Optionen zu compilieren - er gibt dann die Fehlermeldung "Nicht genügend Arbeitsspeicher" aus, sowie den fatalen Fehler, dass das Projekt nicht compiliert werden kann. Da er gar nicht erst compiliert oder in einer Testumgebung keine Fehler meldet, kann ich nicht wirklich breakpoints setzen, um den Fehler zu finden. Der Fehler liegt vermutlich irgendwo beim Zusammenspiel beider Units, genauer kann ich das aber nicht wirklich eingrenzen.

**Comment by ThoJor** [comment]
Ok - klären wir morgen in Informatik. (Hoffentlich)

**Comment by Michail-Okunew** [comment]
Fehlerursache nach Kraut: verzweigungen und falsche Aufrufe der einzelnen Units zueinander.
Lösung: beachten der Beziehungen der jeweiligen Units zueinander beim compilieren und zusammenfügen.
